global:
  dependencies:
    python:
      - forge-sdk==5.0.3
      - forge-cli==5.0.2
      - cecs==5.0.1
      - services/*.py
  env:
    PROJECT_SLUG: "nola"

    LOG_LEVEL: INFO

  repository: "nexus.vingd.net"

  cecs:
    enabled: false
    params: "-e venv"

services:
  rule-engine:
    type: java
    resources:
      cpu: 500m
      memory: 650Mi

  heartbeat:
    type: python
    version: 5.0.1
    env:
      HEARTBEAT_CYCLE: 5
    db:
      mongo: true
    dependencies:
      - rule-engine-api==5.0.2
    resources:
      cpu: 69m
      memory: 65Mi
